name: Docker Image CI

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag latest
